//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.MvcUI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HGS
    {
        public int hgsNo { get; set; }
        public Nullable<decimal> bakiye { get; set; }
    }
}
