//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.MvcUI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Musteriler()
        {
            this.tbl_Hesaplar = new HashSet<tbl_Hesaplar>();
            this.tbl_Iletisim = new HashSet<tbl_Iletisim>();
        }
    
        public int musteriNo { get; set; }
        public string TCKN { get; set; }
        public string sifre { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public string kizlikSoyadi { get; set; }
        public Nullable<bool> musteriTipi { get; set; }
        public Nullable<int> musteriPuani { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Hesaplar> tbl_Hesaplar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Iletisim> tbl_Iletisim { get; set; }
    }
}
