//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.MvcUI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hesaplar
    {
        public int hesapId { get; set; }
        public string musteriNo { get; set; }
        public string hesapNumarasi { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public Nullable<int> krediLimiti { get; set; }
        public Nullable<System.DateTime> hesapAcilisTarihi { get; set; }
        public Nullable<System.DateTime> hesapKapanisTarihi { get; set; }
        public Nullable<int> ekNo { get; set; }
    
        public virtual tbl_Musteriler tbl_Musteriler { get; set; }
    }
}
