//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.MvcUI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Iletisim
    {
        public int iletisimId { get; set; }
        public Nullable<int> musteriId { get; set; }
        public string mail { get; set; }
        public string cepTelefonu { get; set; }
        public string evTelefonu { get; set; }
        public string musteriAdresi { get; set; }
    
        public virtual tbl_Musteriler tbl_Musteriler { get; set; }
    }
}
